name: foundry-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  foundry-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Forge Build
        working-directory: apps/contracts
        run: forge build

      - name: Run Forge Test
        working-directory: apps/contracts
        run: forge test

